const mongoose = require('mongoose');

const attendanceSchema = new mongoose.Schema({
  employee: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Employee',
    required: true
  },
  company: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company',
    required: true
  },
  date: {
    type: Date,
    required: true
  },
  checkIn: {
    type: Date,
    default: null
  },
  checkOut: {
    type: Date,
    default: null
  },
  workHours: {
    type: Number,
    default: 0
  },
  extraHours: {
    type: Number,
    default: 0
  },
  breakHours: {
    type: Number,
    default: 1
  },
  status: {
    type: String,
    enum: ['present', 'absent', 'half_day', 'on_leave', 'holiday', 'weekend'],
    default: 'absent'
  },
  notes: String,
  isAutoGenerated: {
    type: Boolean,
    default: false
  }
}, { 
  timestamps: true 
});

// Compound index to prevent duplicate entries
attendanceSchema.index({ employee: 1, date: 1 }, { unique: true });

// Calculate work hours before saving
attendanceSchema.pre('save', function(next) {
  if (this.checkIn && this.checkOut) {
    const diffMs = this.checkOut - this.checkIn;
    const totalHours = diffMs / (1000 * 60 * 60);
    this.workHours = Math.max(0, parseFloat((totalHours - this.breakHours).toFixed(2)));
    
    const standardHours = 8;
    this.extraHours = Math.max(0, parseFloat((this.workHours - standardHours).toFixed(2)));
    
    if (this.workHours > 0) {
      this.status = this.workHours >= 4 ? 'present' : 'half_day';
    }
  }
  next();
});

module.exports = mongoose.model('Attendance', attendanceSchema);